services:

  django:
    build:
      context: .
      dockerfile: Dockerfile.django
    image: rush_admin/django
    volumes:
      - djangodata:/rush_admin
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      - POSTGRES_DATABASE_HOST=postgres # db container service defined below
      - GDAL_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu/libgdal.so.37 # configure GDAL env path for django (should be stable since we are using a fixed GDAL base image)
    command: >
      sh -c "poetry run python manage.py makemigrations &&
            poetry run python manage.py migrate &&
            poetry run python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"

  postgres:
    image: postgis/postgis:18-3.6
    environment:
      - POSTGRES_DB=${POSTGRES_DATABASE_NAME}
      - POSTGRES_USER=${POSTGRES_DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_DATABASE_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql

volumes:
  djangodata:
  pgdata:
